// Mocks generated by Mockito 5.0.11 from annotations
// in covid_statistics/test/features/statistics/domain/usecases/get_covid_statistics_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:covid_statistics/core/error/failure.dart' as _i5;
import 'package:covid_statistics/features/statistics/domain/entities/covid_statistics.dart'
    as _i6;
import 'package:covid_statistics/features/statistics/domain/repositories/covid_statistics_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [CovidStatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCovidStatisticsRepository extends _i1.Mock
    implements _i3.CovidStatisticsRepository {
  MockCovidStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CovidStatistics>> getCovidStatistics(
          String? date) =>
      (super.noSuchMethod(Invocation.method(#getCovidStatistics, [date]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.CovidStatistics>>.value(
                      _FakeEither<_i5.Failure, _i6.CovidStatistics>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CovidStatistics>>);
}
