// Mocks generated by Mockito 5.0.11 from annotations
// in covid_statistics/test/features/statistics/data/datasources/covid_statistics_local_datasource_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:covid_statistics/core/local_storage/local_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i2.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveData({String? key, String? value}) =>
      (super.noSuchMethod(
          Invocation.method(#saveData, [], {#key: key, #value: value}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<String> getData({String? key}) =>
      (super.noSuchMethod(Invocation.method(#getData, [], {#key: key}),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<void> deleteData({String? key}) =>
      (super.noSuchMethod(Invocation.method(#deleteData, [], {#key: key}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
